FROM golang:1.13-alpine AS hot-reload

WORKDIR /app
RUN apk add --no-cache tzdata git && \
    go get github.com/pilu/fresh

COPY . .

CMD ["fresh"]

FROM golang:1.13-alpine AS builder
WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build -o main .

FROM alpine
WORKDIR /app
RUN apk add --no-cache tzdata

COPY --from=builder /src/main .
COPY conf/conf.yml /app/conf/conf.yml

CMD ["./main"]